# Generated by Django 4.2 on 2025-08-12 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude in decimal degrees (e.g., 37.7749).')),
                ('longitude', models.FloatField(help_text='Longitude in decimal degrees (e.g., -122.4194).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the location was recorded.')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters (optional, for future use).', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters (optional, from device).', null=True)),
                ('user', models.ForeignKey(help_text='The user associated with this GPS location.', on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GPS Location',
                'verbose_name_plural': 'GPS Locations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='gpslocation',
            index=models.Index(fields=['user', 'timestamp'], name='gpsinfo_gps_user_id_a56d44_idx'),
        ),
    ]
