# Generated by Django 4.2 on 2025-08-12 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpsinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslocation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user associated with this GPS location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
