# Generated by Django 4.2 on 2025-08-14 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gpsinfo', '0002_alter_gpslocation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSLatest',
            fields=[
                ('user', models.OneToOneField(help_text='The user associated with this latest GPS location.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gps_latest', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.FloatField(help_text='Latitude in decimal degrees (e.g., 37.7749).')),
                ('longitude', models.FloatField(help_text='Longitude in decimal degrees (e.g., -122.4194).')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters (optional, for future use).', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters (optional, from device).', null=True)),
                ('timestamp', models.DateTimeField(help_text='Time when the location was recorded.')),
            ],
            options={
                'verbose_name': 'Latest GPS Location',
                'verbose_name_plural': 'Latest GPS Locations',
            },
        ),
    ]
